### ISSUE TITLE
Re-organise the GUI for multiple device support.

### ISSUE THREAD

**Issue by lah7** [lah7/razer-chroma-drivers-gui#12]
Currently, the entire GUI is stored within one HTML file, as it was originally created to make key profile configuration easy. :+1: 

Proposed individual pages as a starting point:
* **Devices**
  * All devices connected here will be listed, along with icons and a quick status of what they're doing (eg. battery icon, current effect)
  * #10 will need to be implemented.
 * If there is only one device present, the menu for that product will immediately open.
* **BlackWidow Chroma**
  * Chroma Overview (Main Menu)
  * Chroma Preferences
  * Chroma Profile Editor

Code that should be persistent, such as the header and footer will remain consistent across pages with the help of JavaScript.

I will begin working on the front-end design for this when I finish working on another project.

**Comment by terrycain** [comment]
Nice. I have some thoughts on passing data from webkit to python, I've done a lot of MVC programming so I could employ this here as its well suited. Basically it will drastically simplify the process_command bit to make it tidier, and should be considerably faster too.

**Comment by lah7** [comment]
A basic front end is implemented in 3f347bc17c92cd50e7f0d2e526d1d2d19932665e but won't be used yet as multi-device is not fully implemented in the driver/daemon and isn't a top priority for the GUI.
