### ISSUE TITLE
Port to WebKit2

### ISSUE THREAD

**Issue by lah7** [lah7/razer-chroma-drivers-gui#17]
In some distributions, the infrequency of how often WebKit is updated has caused concern for security.

https://blogs.gnome.org/mcatanzaro/2016/02/01/on-webkit-security-updates/

The application can be ported to `webkit2gtk`, which is available via the package `gir1.2-webkit2-4.0` for Ubuntu/Debian distros. There's some added benefits too, like more up-to-date web technologies, smoother rendering and better use of hardware for rendering.

**Comment by terrycain** [comment]
Is there any major differences in the libraries interface? If not shouldn't be too difficult to port. Though I'd wait until we have a stable release before we get everyone to install yet another package.

**Comment by lah7** [comment]
Some differences, like `execute_script()` becomes `run_javascript()`. I had started porting another project's, but haven't yet found how to catch URIs like `cmd://do-something`.

You're right, and probably better to do so after the release of Ubuntu 16.04, since this package might not be in Ubuntu 14.04.

**Comment by terrycain** [comment]
Can you get a event when the title is changed, that's what the docs recommended. It would probably be worth changing the app to follow a model view controller approach, that would separate out the logic nicely too.

**Comment by lah7** [comment]
Feel free to change the logic of the program as you see fit when you've completed your studies. I'm focused working on other OSS projects for now.

I remember you [mentioning](https://github.com/lah7/razer-chroma-drivers-gui/issues/12#issuecomment-171446450) about MVC a while back. The port to WebKit2 would be a good time to re-organise code internally, as you say, once we get a stable package out.

> Nice. I have some thoughts on passing data from webkit to python, I've done a lot of MVC programming so I could employ this here as its well suited. Basically it will drastically simplify the process_command bit to make it tidier, and should be considerably faster too.

_I'll briefly mention that both the GUI/Tray Applet work well. Some issues may arise if my system went sleeping though._

**Comment by terrycain** [comment]
It stops working when you put things to sleep? 

Im working with another guy trying to get some technical docs from razer, that might be good if we get them, Yeah would be a good time to restructure things.

**Comment by lah7** [comment]
Not always -- quite rarely actually -- if the tray applet has been running for hours with some sleeps, it may start to misbehave / utilize the process' CPU to 100%.

Going off-topic, so WebKit2 porting... sometime after Ubuntu 16.04. We'll need to check if other distros have the package too.

**Comment by terrycain** [comment]
Yeah good point, if its availability is limited than it would be annoying to switch, as ideally we want to use python packages available from the systems package manager. I think we progress with restructuring and keep the webkit porting at the back of our minds for now.

And that's odd, I would expect the 100% utilisation when a loop spins without any sleeps in it but I don't there is anything like that in the tray app. Could be a bug with whatever event loop it uses
