### ISSUE TITLE
Import/Export Functionality

### ISSUE THREAD

**Issue by lah7** [lah7/razer-chroma-drivers-gui#4]
While only compatible with other GNU/Linux users, it would allow :penguin: users to easily share their key profiles with others.

**Comment by terrycain** [comment]
They could just copy the binary files in `~/.config/razer_chroma/profiles` to other people.

Or going overboard one could create a web application which is like "the cloud" which users can store and share profiles. Might do this at some point.

**Comment by lah7** [comment]
So it'll probably be better to consider a button to open the profiles/config folder instead.

No need for going overboard - users can use cloud services like Dropbox, ownCloud and Bittorrent Sync to transfer their settings across computers. Integration with these services may be a better route.

**Comment by terrycain** [comment]
My mate was keen to make a web app ;), that's the only reason I offered. I hate creating proper web apps lol. But yes a button to open the file browser would be useful.
